databases:
  - name: mysite
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: mysite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        
# services:
#   - type: web
#     name: budget_wizard
#     env: ruby
#     # buildCommand: "./bin/render-build.sh"
#     # startCommand: "bundle exec puma -C config/puma.rb"
#     buildCommand: bundle install
#     startCommand: bundle exec ruby main.rb
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase: 
#           name: bw_db
#           property: connectionString
#       - key: SECRET_KEY_BASE
#         generateValue: true
